
create table if not exists materials (
  name text primary key,
  price numeric not null default 0
);

create table if not exists crafts (
  id bigint generated by default as identity primary key,
  name text not null,
  table_name text not null,
  output_qty numeric not null default 1,
  sort_order bigint default 0,
  image_url text default '',
  sale_percentage numeric not null default 25
);

create table if not exists craft_ingredients (
  id bigint generated by default as identity primary key,
  craft_id bigint references crafts(id) on delete cascade,
  material_name text not null,
  qty numeric not null default 1,
  sort_order int default 0
);


create table if not exists craft_tables (
  name text primary key,
  tag text not null,
  color text not null,
  sort_order bigint not null default 0
);

create table if not exists settings (
  id text primary key,
  value numeric not null
);

alter table materials enable row level security;
alter table crafts enable row level security;
alter table craft_ingredients enable row level security;
alter table settings enable row level security;
alter table craft_tables enable row level security;

drop policy if exists "public read materials" on materials;
drop policy if exists "public insert materials" on materials;
drop policy if exists "public update materials" on materials;
drop policy if exists "public delete materials" on materials;
create policy "public read materials" on materials for select using (true);
create policy "public insert materials" on materials for insert with check (true);
create policy "public update materials" on materials for update using (true);
create policy "public delete materials" on materials for delete using (true);

drop policy if exists "public read crafts" on crafts;
drop policy if exists "public insert crafts" on crafts;
drop policy if exists "public update crafts" on crafts;
drop policy if exists "public delete crafts" on crafts;
create policy "public read crafts" on crafts for select using (true);
create policy "public insert crafts" on crafts for insert with check (true);
create policy "public update crafts" on crafts for update using (true);
create policy "public delete crafts" on crafts for delete using (true);

drop policy if exists "public read ingredients" on craft_ingredients;
drop policy if exists "public insert ingredients" on craft_ingredients;
drop policy if exists "public update ingredients" on craft_ingredients;
drop policy if exists "public delete ingredients" on craft_ingredients;
create policy "public read ingredients" on craft_ingredients for select using (true);
create policy "public insert ingredients" on craft_ingredients for insert with check (true);
create policy "public update ingredients" on craft_ingredients for update using (true);
create policy "public delete ingredients" on craft_ingredients for delete using (true);


drop policy if exists "public read craft tables" on craft_tables;
drop policy if exists "public insert craft tables" on craft_tables;
drop policy if exists "public update craft tables" on craft_tables;
drop policy if exists "public delete craft tables" on craft_tables;
create policy "public read craft tables" on craft_tables for select using (true);
create policy "public insert craft tables" on craft_tables for insert with check (true);
create policy "public update craft tables" on craft_tables for update using (true);
create policy "public delete craft tables" on craft_tables for delete using (true);

drop policy if exists "public read settings" on settings;
drop policy if exists "public insert settings" on settings;
drop policy if exists "public update settings" on settings;
create policy "public read settings" on settings for select using (true);
create policy "public insert settings" on settings for insert with check (true);
create policy "public update settings" on settings for update using (true);

-- Liga realtime/sincronização. Se alguma linha der erro por já existir, podes ignorar.
alter publication supabase_realtime add table materials;
alter publication supabase_realtime add table crafts;
alter publication supabase_realtime add table craft_ingredients;
alter publication supabase_realtime add table settings;
alter publication supabase_realtime add table craft_tables;
